name: Docker Image CI
on:
  pull_request:
    types:
      - closed
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:

  Build_Secure_Image:

    runs-on: ubuntu-latest
    name: Set environmental variables for Prisma Cloud access
    env: 
      TL_USER: ${{ secrets.TL_USER }}
      TL_PASS: ${{ secrets.TL_PASS }}
      TL_CONSOLE: ${{ secrets.TL_CONSOLE }} 
      BYPASS_REPOSCAN: 1
      BYPASS_OSS_LICENSE: 1
      BYPASS_IMAGESCAN: 0
      BYPASS_WF: 1
      BYPASS_SANDBOX: 1

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vulnerable-test:$(date +%s)

    - name: check images
      run: docker images

    - name: Download twistcli
      run: curl -s -k -u $TL_USER:$TL_PASS "https://$TL_CONSOLE/api/v1/util/twistcli" -v -o twistcli;chmod +x twistcli
    
    - name: Scan image for vulns and compliance issues
      run: ./twistcli images scan --u $TL_USER --p $TL_PASS --address https://$TL_CONSOLE --details vulnerable-test -o output.json
